spring:
  application:
    name: bankingapp-account-service
#  config:
#    import: "optional:configserver:"
  cloud:
    config:
      discovery:
        enabled: false
        service-id: bankingapp-config-service
  datasource:
    url: jdbc:postgresql://localhost:5432/bankingapp-account-service
    username: postgres
    password: postgres
  kafka:
    bootstrap-servers: localhost:9092
#
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    format_sql: true
  h2:
    console:
      enabled: true
#
server:
  port: 8091
#
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761
    register-with-eureka: true
    fetch-registry: true

bankingapp:
  kafka:
    topic:
      fund-transfers: fundTransferStatus
#
management:
  endpoints:
    web:
      exposure:
        include: "*"